(() => {
  const POSITION_KEY='mein-uebersetzer-position',DEBOUNCE_MS=220;
  let panel=null,drag=null,requestId=0,lastSelectedText='',debounceTimer=null;
  const selectedText=()=>window.getSelection()?.toString().trim()||'';
  const hidePanel=()=>{if(panel)panel.style.display='none';};
  function fitPanel(){if(!panel)return;const maxW=Math.max(180,Math.min(innerWidth*.5,innerWidth-24));panel.style.width='max-content';panel.style.maxWidth=maxW+'px';if(panel.getBoundingClientRect().width>maxW)panel.style.width=maxW+'px';}
  function ensurePanel(){if(panel)return;panel=document.createElement('div');panel.id='mein-uebersetzer-panel';panel.setAttribute('role','status');panel.innerHTML='<div class="mein-uebersetzer-handle">⠿ Übersetzung</div><div class="mein-uebersetzer-text"></div><div class="mein-uebersetzer-actions"><button class="copy-button" type="button">Kopieren</button><button class="save-button" type="button">Vokabel speichern</button></div>';document.documentElement.appendChild(panel);const h=panel.firstElementChild;h.addEventListener('pointerdown',startDrag);h.addEventListener('pointermove',moveDrag);h.addEventListener('pointerup',endDrag);h.addEventListener('pointercancel',endDrag);panel.querySelector('.copy-button').addEventListener('click',()=>navigator.clipboard?.writeText(panel.dataset.original+' = '+panel.querySelector('.mein-uebersetzer-text').textContent));panel.querySelector('.save-button').addEventListener('click',()=>{const list=JSON.parse(localStorage.getItem('mein-uebersetzer-vocabulary')||'[]');list.push({original:panel.dataset.original,translation:panel.querySelector('.mein-uebersetzer-text').textContent,date:new Date().toISOString()});localStorage.setItem('mein-uebersetzer-vocabulary',JSON.stringify(list));});try{const p=JSON.parse(localStorage.getItem(POSITION_KEY)||'null');if(p){panel.style.left=p.left+'px';panel.style.top=p.top+'px';panel.style.right='auto';panel.style.bottom='auto';}}catch{}}
  function startDrag(e){if(!panel||e.button!==0)return;const r=panel.getBoundingClientRect();drag={id:e.pointerId,x:e.clientX-r.left,y:e.clientY-r.top};e.currentTarget.setPointerCapture(e.pointerId);panel.classList.add('dragging');e.preventDefault();}
  function moveDrag(e){if(!drag||e.pointerId!==drag.id)return;panel.style.left=e.clientX-drag.x+'px';panel.style.top=e.clientY-drag.y+'px';panel.style.right='auto';panel.style.bottom='auto';}
  function endDrag(e){if(!drag||e.pointerId!==drag.id)return;try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{}const r=panel.getBoundingClientRect();localStorage.setItem(POSITION_KEY,JSON.stringify({left:r.left,top:r.top}));panel.classList.remove('dragging');drag=null;}
  function showLoading(text){ensurePanel();panel.dataset.original=text;panel.querySelector('.mein-uebersetzer-text').textContent='Übersetze …';panel.querySelectorAll('button').forEach(b=>b.disabled=true);panel.style.display='block';fitPanel();}
  function showResult(text){panel.querySelector('.mein-uebersetzer-text').textContent=text;panel.querySelectorAll('button').forEach(b=>b.disabled=false);fitPanel();}
  function requestTranslation(text){clearTimeout(debounceTimer);showLoading(text);debounceTimer=setTimeout(()=>{const id=++requestId;chrome.runtime.sendMessage({type:'translate',text},r=>{if(id!==requestId)return;if(chrome.runtime.lastError||!r){hidePanel();return;}if(r.skip){hidePanel();return;}if(r.error){panel.querySelector('.mein-uebersetzer-text').textContent='Übersetzung nicht verfügbar';return;}if(selectedText()!==text){hidePanel();return;}if(r.translation)showResult(r.translation);});},DEBOUNCE_MS);}
  document.addEventListener('selectionchange',()=>{const s=selectedText();if(!s){requestId++;clearTimeout(debounceTimer);lastSelectedText='';hidePanel();return;}if(s!==lastSelectedText){lastSelectedText=s;requestTranslation(s);}});
  document.addEventListener('mouseup',()=>{const s=selectedText();if(s&&s!==lastSelectedText){lastSelectedText=s;requestTranslation(s);}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape')hidePanel();});window.addEventListener('resize',fitPanel);
})();
